spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhengjie0101
    url: jdbc:mysql://127.0.0.1/mall?characterEncoding=utf-8&useSSL=false
  rabbitmq:
    addresses:
    port: 5672
    username: guset
    password: guest
  redis:
    host: 192.168.0.104
    port: 6379
    password: redis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 控制台配置打印mysql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mappers/*.xml